### ISSUE TITLE
problem z dodaniem nowej playlisty 

### ISSUE THREAD

**Issue by nowehity97** [workonfire/WziumDio#1]
mam taki problem chcę dodać pyliste z open fm https://open.fm/api/api-ext/v2/channels/long.json, i mam problem jak to dodać do sources.

**Comment by workonfire** [comment]
**Na czym dokładnie polega Twój problem?**

By dodać kolejną stację radiową i jej własną playlistę, należy:
1. Przypisać jej nazwę i alias w pliku `aliases.json` (odpowiednio: *alias -> nazwa wyświetlana*).
2. Przypisać aliasowi nowo dodanej stacji **adres streamingu** i **bezpośredni adres do playlisty** w formacie JSON (w pliku `sources.json`)
3. Stworzyć nową klasę w katalogu `playlists`. Klasa ta powinna implementować interfejs `Playlist`. Jedyna metoda w tym interfejsie powinna odpowiednio przetwarzać playlistę z danych przekazanych w konstruktorze tejże klasy (są to dane JSON skonwertowane do typu `array`), a następnie zwracać wynik w postaci jakiegoś ładnego `div`'a.
4. Zmodyfikować metodę wytwórczą `createPlaylist` w klasie `Radio`, by zwracała nam odpowiednią stację radiową dla dopiero stworzonego aliasu.

Nie daję przykładów, bo myślę, że to co jest już w folderze z playlistami, jest już wystarczające.

Jak przetworzyć te dane JSON - to już trzeba samemu ogarnąć, każda stacja radiowa jest inna i inaczej przechowuje dane. Ja wszystko robiłem metodą prób i błędów, chociaż tutaj to pewnie będzie wystarczyło odwołać się do konkretnego numerka w tablicy, a następnie do kolejnych indeksów. Nie wiem. Na razie jestem zawalony robotą i nie mam czasu zerknąć, jak jest zbudowana ta playlista.

Jeśli jednak bardzo chcesz i będę miał czas, mogę pododawać kilka stacji OpenFM. Samemu słucham tego radia, czekając z kolegami na kebaba :smiley:

**Comment by nowehity97** [comment]
> **Na czym dokładnie polega Twój problem?**
> 
> By dodać kolejną stację radiową i jej własną playlistę, należy:
> 
> 1. Przypisać jej nazwę i alias w pliku `aliases.json` (odpowiednio: _alias -> nazwa wyświetlana_).
> 2. Przypisać aliasowi nowo dodanej stacji **adres streamingu** i **bezpośredni adres do playlisty** w formacie JSON (w pliku `sources.json`)
> 3. Stworzyć nową klasę w katalogu `playlists`. Klasa ta powinna implementować interfejs `Playlist`. Jedyna metoda w tym interfejsie powinna odpowiednio przetwarzać playlistę z danych przekazanych w konstruktorze tejże klasy (są to dane JSON skonwertowane do typu `array`), a następnie zwracać wynik w postaci jakiegoś ładnego `div`'a.
> 4. Zmodyfikować metodę wytwórczą `createPlaylist` w klasie `Radio`, by zwracała nam odpowiednią stację radiową dla dopiero stworzonego aliasu.
> 
> Nie daję przykładów, bo myślę, że to co jest już w folderze z playlistami, jest już wystarczające.
> 
> Jak przetworzyć te dane JSON - to już trzeba samemu ogarnąć, każda stacja radiowa jest inna i inaczej przechowuje dane. Ja wszystko robiłem metodą prób i błędów, chociaż tutaj to pewnie będzie wystarczyło odwołać się do konkretnego numerka w tablicy, a następnie do kolejnych indeksów. Nie wiem. Na razie jestem zawalony robotą i nie mam czasu zerknąć, jak jest zbudowana ta playlista.
> 
> Jeśli jednak bardzo chcesz i będę miał czas, mogę pododawać kilka stacji OpenFM. Samemu słucham tego radia, czekając z kolegami na kebaba 😃

Tak kilka stacji rmf sam dodałem, tylko nie wiem zabardzo jak dodać te open FM bo ta lista jest jako jedna strona i jest trochę inaczej niż RMF, jak byś chciał przykładowy steam open fm http://stream.open.fm/2 --> Impreza

**Comment by workonfire** [comment]
No racja, ta lista jest trochę inna. Na razie sam nie wiem jak to zrobić, musiałbym przysiąść i to przeanalizować. A jak znajdę czas i to zrobię, to od razu wrzucę do mastera tutaj. Także nie zamykam tego, żeby nie zapomnieć.

**Comment by nowehity97** [comment]
> No racja, ta lista jest trochę inna. Na razie sam nie wiem jak to zrobić, musiałbym przysiąść i to przeanalizować. A jak znajdę czas i to zrobię, to od razu wrzucę do mastera tutaj. Także nie zamykam tego, żeby nie zapomnieć.

można do ciebie jakiś kontakt prv, discord na przykład

**Comment by nowehity97** [comment]
> No racja, ta lista jest trochę inna. Na razie sam nie wiem jak to zrobić, musiałbym przysiąść i to przeanalizować. A jak znajdę czas i to zrobię, to od razu wrzucę do mastera tutaj. Także nie zamykam tego, żeby nie zapomnieć.

można do ciebie jakiś kontakt prv, discord na przykład
